type types = {
  FETCH_COUNTRIES: 'FETCH_COUNTRIES',
  FETCH_STATES: 'FETCH_STATES',
  FETCH_CITIES: 'FETCH_CITIES',
  SET_SELECTED_COUNTRY: 'SET_SELECTED_COUNTRY',
  SET_SELECTED_STATE: 'SET_SELECTED_STATE',
  SET_SELECTED_CITY: 'SET_SELECTED_CITY',
  REQUESTED_COUNTRY_DATA: 'REQUESTED_COUNTRY_DATA',
  REQUESTED_COUNTRY_DATA_SUCCEEDED: 'REQUESTED_COUNTRY_DATA_SUCCEEDED',
  REQUESTED_COUNTRY_DATA_FAILED: 'REQUESTED_COUNTRY_DATA_FAILED',
  REQUESTED_STATE_DATA: 'REQUESTED_STATE_DATA',
  REQUESTED_STATE_DATA_SUCCEEDED: 'REQUESTED_STATE_DATA_SUCCEEDED',
  REQUESTED_STATE_DATA_FAILED: 'REQUESTED_STATE_DATA_FAILED',
  REQUESTED_CITY_DATA: 'REQUESTED_CITY_DATA',
  REQUESTED_CITY_DATA_SUCCEEDED: 'REQUESTED_CITY_DATA_SUCCEEDED',
  REQUESTED_CITY_DATA_FAILED: 'REQUESTED_CITY_DATA_FAILED',
};

const actionTypes: types = {
  FETCH_COUNTRIES: 'FETCH_COUNTRIES',
  FETCH_STATES: 'FETCH_STATES',
  FETCH_CITIES: 'FETCH_CITIES',
  SET_SELECTED_COUNTRY: 'SET_SELECTED_COUNTRY',
  SET_SELECTED_STATE: 'SET_SELECTED_STATE',
  SET_SELECTED_CITY: 'SET_SELECTED_CITY',
  REQUESTED_COUNTRY_DATA: 'REQUESTED_COUNTRY_DATA',
  REQUESTED_COUNTRY_DATA_SUCCEEDED: 'REQUESTED_COUNTRY_DATA_SUCCEEDED',
  REQUESTED_COUNTRY_DATA_FAILED: 'REQUESTED_COUNTRY_DATA_FAILED',
  REQUESTED_STATE_DATA: 'REQUESTED_STATE_DATA',
  REQUESTED_STATE_DATA_SUCCEEDED: 'REQUESTED_STATE_DATA_SUCCEEDED',
  REQUESTED_STATE_DATA_FAILED: 'REQUESTED_STATE_DATA_FAILED',
  REQUESTED_CITY_DATA: 'REQUESTED_CITY_DATA',
  REQUESTED_CITY_DATA_SUCCEEDED: 'REQUESTED_CITY_DATA_SUCCEEDED',
  REQUESTED_CITY_DATA_FAILED: 'REQUESTED_CITY_DATA_FAILED',
}

export default actionTypes;